/**
 * Confluence REST API helper — creates or updates a page
 * linked to a Jira issue.
 */

const { requestConfluence, storage } = require("@forge/api");

const STORAGE_PREFIX = "docufish:page:";

/**
 * Creates a new Confluence page (or updates an existing one for this issue).
 *
 * @param {string} spaceKey     - Target Confluence space
 * @param {string} issueKey     - Jira issue key (e.g. "PROJ-42")
 * @param {string} title        - Page title
 * @param {string} storageBody  - Confluence Storage Format content
 * @returns {Promise<string>}   - URL of the created/updated page
 */
async function upsertPage(spaceKey, issueKey, title, storageBody) {
  const storageKey = `${STORAGE_PREFIX}${issueKey}`;
  const existingPageId = await storage.get(storageKey);

  if (existingPageId) {
    return updatePage(existingPageId, title, storageBody, issueKey);
  }

  return createPage(spaceKey, title, storageBody, storageKey, issueKey);
}

async function createPage(spaceKey, title, storageBody, storageKey, issueKey) {
  const response = await requestConfluence(`/wiki/rest/api/content`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json" },
    body: JSON.stringify({
      type: "page",
      title: `[DocuFish] ${title}`,
      space: { key: spaceKey },
      body: {
        storage: {
          value: addDocuFishHeader(storageBody, issueKey),
          representation: "storage",
        },
      },
    }),
  });

  const data = await response.json();
  const pageId = data.id;
  const pageUrl = data._links?.webui;

  await storage.set(storageKey, pageId);

  return pageUrl;
}

async function updatePage(pageId, title, storageBody, issueKey) {
  // Get current version first
  const current = await requestConfluence(`/wiki/rest/api/content/${pageId}`, {
    method: "GET",
    headers: { Accept: "application/json" },
  });
  const currentData = await current.json();
  const nextVersion = currentData.version.number + 1;

  const response = await requestConfluence(`/wiki/rest/api/content/${pageId}`, {
    method: "PUT",
    headers: { "Content-Type": "application/json", Accept: "application/json" },
    body: JSON.stringify({
      type: "page",
      title: `[DocuFish] ${title}`,
      version: { number: nextVersion },
      body: {
        storage: {
          value: addDocuFishHeader(storageBody, issueKey),
          representation: "storage",
        },
      },
    }),
  });

  const data = await response.json();
  return data._links?.webui;
}

function addDocuFishHeader(body, issueKey) {
  return `
<ac:structured-macro ac:name="info">
  <ac:parameter ac:name="title">Generated by DocuFish</ac:parameter>
  <ac:rich-text-body>
    <p>This page was automatically generated from Jira ticket <strong>${issueKey}</strong>
    using <a href="https://github.com/carloco1/wurmspiele">DocuFish</a> + MiroFish multi-agent simulation.
    Last updated: ${new Date().toISOString()}</p>
  </ac:rich-text-body>
</ac:structured-macro>
${body}
`.trim();
}

module.exports = { upsertPage };
