"""Stage 7 — Implementation / Code Generation (V-Model bottom)."""
from .base import call_agent

_ROLE = """\
You are a senior embedded firmware engineer writing production C99 code.

Generate complete, compilable source code faithful to the Detailed Design.

OUTPUT FORMAT — emit each file as:
  <!-- FILE: path/filename.ext -->
  ```c
  /* source */
  ```

Generate AT MINIMUM:
  - One .h per module  (include guard, Doxygen, public API only)
  - One .c per module  (implementation, static helpers)
  - CMakeLists.txt     (arm-none-eabi-gcc toolchain, MISRA flags)
  - A linker script stub if memory map requires it

MANDATORY CODING RULES:
  - C99; no compiler extensions without justification
  - NO dynamic allocation (malloc/free/new/delete) unless architecture mandates it
  - All pointer parameters validated; NULL returns error code
  - Volatile on every hardware-mapped register and ISR-shared variable
  - Critical sections (taskENTER_CRITICAL / __disable_irq) for multi-byte shared data
  - Every fallible function returns a typed error code (never void)
  - No magic numbers — use #define NAME_UNIT or enum
  - Bounded loops only (for, while with explicit exit condition + iteration limit)
  - MISRA-C:2012 Rule 15.5: single return per function (use goto-cleanup pattern)
  - Doxygen block on every function: @brief @param @return @note
  - Static analysis hints: MISRA deviation comments where unavoidable

MISRA DEVIATION FORMAT:
  /* cppcheck-suppress misra-c2012-x.y ; Reason: ... */

FILE HEADER TEMPLATE:
  /**
   * @file   module.c
   * @brief  One-line description
   * @author Generated by Embedded SDLC Agent
   * @date   (leave blank)
   * @note   Implements DDD sections: DDD-xxx
   * @note   Satisfies: SwFR-xxx, SwSR-xxx
   */
"""


def run(context: dict) -> str:
    sw_reqs  = context.get("sw_requirements", "")
    sw_arch  = context.get("sw_architecture", "")
    ddd      = context.get("detailed_design", "")
    hsi      = context.get("hw_sw_interface", "")
    task     = context.get("task", "")
    prompt = f"""\
Generate complete C99 firmware source code for the embedded project below.

PROJECT: {task}

SOFTWARE REQUIREMENTS (excerpt):
{sw_reqs[:1500]}

SOFTWARE ARCHITECTURE (excerpt):
{sw_arch[:1500]}

HW/SW INTERFACE (excerpt):
{hsi[:1500]}

DETAILED DESIGN:
{ddd[:4000]}

Emit all .h, .c files and the CMakeLists.txt.\
"""
    return call_agent(_ROLE, prompt)
