/**
 * DocuFish — Confluence Content Byline
 * Shows a small "generated by DocuFish" badge on generated pages.
 */

import ForgeUI, {
  render,
  ContentBylineItem,
  Fragment,
  Text,
  Badge,
} from "@forge/ui";

const Byline = () => (
  <Fragment>
    <Badge appearance="primary" text="DocuFish" />
    <Text>Auto-generated via MiroFish simulation</Text>
  </Fragment>
);

export const run = render(
  <ContentBylineItem>
    <Byline />
  </ContentBylineItem>
);
